# Generated by Django 5.0.6 on 2024-10-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзину', 'verbose_name_plural': 'Корзины'},
        ),
    ]
