# Generated by Django 5.0.6 on 2024-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('coment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Фото')),
                ('city', models.TextField(blank=True, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'адресс',
                'verbose_name_plural': 'Адресса',
                'db_table': 'email_for_mailing',
            },
        ),
    ]
