# Generated by Django 5.0.6 on 2024-09-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Пользователь'),
        ),
    ]
