# Generated by Django 5.0.6 on 2024-09-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comment_city_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_user_images', verbose_name='Фото'),
        ),
    ]
