# Generated by Django 5.0.6 on 2024-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Город'),
        ),
    ]
