# Generated by Django 5.0.6 on 2024-09-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment',
            new_name='text',
        ),
    ]
