# Generated by Django 5.0.6 on 2024-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_products_featured_item_products_new_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Пол')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'пол',
                'verbose_name_plural': 'Полы',
                'db_table': 'зeople_category',
            },
        ),
    ]
