# Generated by Django 5.0.6 on 2024-09-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_people_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='products',
            name='sizе',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Размер'),
        ),
    ]
