# Generated by Django 5.0.6 on 2024-09-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_brand_products_rating_products_sizе'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='people_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.people_categorys', verbose_name='Пол'),
        ),
    ]
