# Generated by Django 5.0.6 on 2024-09-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_products_people_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
