# Generated by Django 5.0.6 on 2024-10-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people_categorys',
            table='people_category',
        ),
    ]
