# Generated by Django 5.0.6 on 2024-10-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0009_alter_people_categorys_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Название компании')),
                ('country', models.CharField(max_length=150, null=True, verbose_name='Страна')),
                ('delivery_address', models.TextField(max_length=400, null=True, verbose_name='Адресс доставки')),
                ('optionally_delivery_address', models.TextField(blank=True, max_length=400, verbose_name='Дополнительно к адресу')),
                ('city', models.CharField(max_length=150, null=True, verbose_name='Город')),
                ('state', models.CharField(max_length=150, null=True, verbose_name='Регион')),
                ('index_cod', models.CharField(max_length=150, null=True, verbose_name='Индекс')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=150, null=True, verbose_name='Почта')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='Оплата при получении')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('status', models.CharField(default='В обработке', max_length=50, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='Количество')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.products', verbose_name='Проудкт')),
            ],
            options={
                'verbose_name': 'Проданный товар',
                'verbose_name_plural': 'Проданный товар',
                'db_table': 'order_item',
            },
        ),
    ]
