# Generated by Django 5.0.6 on 2024-10-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='optionally_delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_on_get',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_inforation',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Дополнительная информация'),
        ),
    ]
